package:
  name: deepsvr
  version: "0.1.0"

source:
  path: .

build:
  script:
    - flake8 . -v --config=.flake8rc
    - nosetests --verbose
    - python setup.py install
  entry_points:
    - deepsvr = deepsvr.cli:main

requirements:
  build:
    - python
    - setuptools
    - nose
    - flake8
    - pandas
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
    - bam-readcount
    - convert_zero_one_based
    - click
    - tensorflow
    - keras
    - scikit-learn
    - h5py
  run:
    - python
    - bam-readcount
    - pandas
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
    - convert_zero_one_based
    - click
    - tensorflow
    - keras
    - scikit-learn
    - h5py

test:
  requires:
    - nose
  imports:
    - deepsvr


about:
  home: https://github.com/griffithlab/deepsvr
  license: MIT
